# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 OKPF Contributors
"""Demo mode: self-contained end-to-end OKPF showcase."""

from __future__ import annotations

import hashlib
import json
import shutil
import tempfile
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from uuid import uuid4

from okpf_validate import validate_pack, load_manifest
from okpf.eval.auto_generate import auto_generate_questions


def create_demo_pack(source_file: str) -> tuple[str, Path]:
    """Create a demo OKPF pack from a source document.

    Args:
        source_file: Path to input Markdown or text file

    Returns:
        Tuple of (output_kpack_path, temp_pack_dir)
    """
    source_path = Path(source_file).resolve()
    if not source_path.is_file():
        raise FileNotFoundError(f"Source file not found: {source_file}")

    temp_dir = Path(tempfile.mkdtemp(prefix="okpf_demo_"))

    manifest = _build_manifest(source_path)
    manifest_path = temp_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    content_dir = temp_dir / "content"
    content_dir.mkdir()
    content_file = content_dir / source_path.name
    shutil.copy2(source_path, content_file)

    provenance = _build_provenance(source_path)
    provenance_path = temp_dir / "provenance.json"
    provenance_path.write_text(json.dumps(provenance, indent=2), encoding="utf-8")

    source_text = source_path.read_text(encoding="utf-8")
    questions = auto_generate_questions(source_text, max_questions=3)

    evaluations_dir = temp_dir / "evaluations"
    evaluations_dir.mkdir()
    evals_data = {
        "evaluations": [
            {
                "id": q.id,
                "type": "short_answer",
                "question": q.question,
                "expected_answer": q.expected_answer,
            }
            for q in questions
        ]
    }
    evals_path = evaluations_dir / "auto.json"
    evals_path.write_text(json.dumps(evals_data, indent=2), encoding="utf-8")

    artifact_entry = manifest["artifacts"][0]
    with open(content_file, "rb") as f:
        file_hash = hashlib.sha256(f.read()).hexdigest()
        artifact_entry["sha256"] = file_hash

    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    kpack_file = Path.cwd() / f"demo-{uuid4().hex[:8]}.kpack"
    _pack_directory(temp_dir, kpack_file)

    return str(kpack_file), temp_dir


def _build_manifest(source_path: Path) -> dict:
    """Build a manifest for the demo pack."""
    package_id = f"okpf-demo-{uuid4().hex[:8]}"
    artifact_name = source_path.stem or "content"

    return {
        "$schema": "https://okpf.org/schema/v0.1.0/manifest.schema.json",
        "okpf_version": "0.1.0",
        "package_id": package_id,
        "name": f"Demo Pack: {source_path.stem}",
        "version": "1.0.0",
        "domain": "general",
        "created": datetime.now(UTC).isoformat() + "Z",
        "description": f"Auto-generated demo pack from {source_path.name}",
        "license": {
            "type": "CC-BY-4.0",
            "details": "Demo content. Attribution appreciated.",
        },
        "usage_policy": {
            "allow_rag": True,
            "allow_fine_tuning": False,
            "allow_evaluation": True,
            "allow_commercial_use": False,
            "allow_derivatives": True,
            "require_attribution": True,
            "notes": "Demo pack auto-generated by okpf demo command.",
        },
        "artifacts": [
            {
                "path": f"content/{source_path.name}",
                "type": "text/markdown" if source_path.suffix == ".md" else "text/plain",
                "title": f"Source: {source_path.name}",
                "role": "guide",
                "description": "Auto-imported source document",
            }
        ],
        "evaluations": [
            {"$ref": "evaluations/auto.json"}
        ],
        "profiles": ["okpf-core"],
    }


def _build_provenance(source_path: Path) -> dict:
    """Build provenance metadata."""
    return {
        "sources": [
            {
                "type": "original",
                "path": str(source_path.name),
                "timestamp": datetime.now(UTC).isoformat() + "Z",
            }
        ],
        "transformations": [
            {
                "type": "manual",
                "description": "Imported via okpf demo command",
                "timestamp": datetime.now(UTC).isoformat() + "Z",
            }
        ],
    }


def _pack_directory(pack_dir: Path, output_file: Path) -> None:
    """Create a ZIP archive from a pack directory."""
    with zipfile.ZipFile(output_file, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file_path in sorted(pack_dir.rglob("*")):
            if file_path.is_file():
                rel_path = file_path.relative_to(pack_dir)
                entry_name = "/".join(rel_path.parts)
                zf.write(file_path, entry_name)


def validate_demo_pack(pack_path: str) -> bool:
    """Validate the demo pack and print results."""
    result = validate_pack(pack_path)

    if result.valid:
        print(f"✓ OKPF package is valid: {result.package_id or pack_path}")
        for warning in result.warnings:
            print(f"  {warning}")
    else:
        print(f"✗ OKPF package is invalid: {pack_path}")
        for error in result.errors:
            print(f"  {error}")
        for warning in result.warnings:
            print(f"  {warning}")

    return result.valid


def inspect_pack_summary(pack_path: str) -> None:
    """Print a human-readable pack summary."""
    manifest, errors = load_manifest(pack_path)
    if manifest is None:
        print(f"✗ Could not inspect package: {pack_path}")
        for error in errors:
            print(f"  {error}")
        return

    artifacts = manifest.get("artifacts", []) + manifest.get("content", [])
    evaluations_ref = manifest.get("evaluations", [])
    eval_count = 0

    if evaluations_ref:
        if isinstance(evaluations_ref, list) and evaluations_ref:
            first = evaluations_ref[0]
            if isinstance(first, dict) and "$ref" in first:
                eval_count = _load_eval_count(pack_path, first["$ref"])

    print("\n=== Pack Summary ===")
    print(f"Package ID:      {manifest.get('package_id') or manifest.get('id') or '(none)'}")
    print(f"Name:            {manifest.get('name') or '(untitled)'}")
    print(f"Version:         {manifest.get('version') or '(none)'}")
    print(f"Domain:          {manifest.get('domain') or '(none)'}")
    print(f"Artifacts:       {len(artifacts)}")
    print(f"Evaluations:     {eval_count}")
    print(f"License:         {manifest.get('license', {}).get('type', '(none)')}")
    print()


def _load_eval_count(pack_path: str, ref_path: str) -> int:
    """Load the count of evaluations from a pack."""
    evals_data = _load_evaluations(pack_path, ref_path)
    if evals_data:
        return len(evals_data.get("evaluations", []))
    return 0


def _load_evaluations(pack_path: str, ref_path: str) -> dict | None:
    """Load evaluations from a pack, handling both directory and ZIP files."""
    pack_path_obj = Path(pack_path)

    if pack_path_obj.is_file() and pack_path_obj.suffix == ".kpack":
        try:
            with zipfile.ZipFile(pack_path_obj, "r") as zf:
                content = zf.read(ref_path).decode("utf-8")
                return json.loads(content)
        except Exception:
            return None
    else:
        ref_file = pack_path_obj / ref_path if pack_path_obj.is_dir() else pack_path_obj.parent / ref_path
        if ref_file.is_file():
            return json.loads(ref_file.read_text(encoding="utf-8"))
    return None


def run_eval_quiz(pack_path: str) -> None:
    """Run an interactive evaluation quiz."""
    manifest, errors = load_manifest(pack_path)
    if manifest is None:
        print("✗ Could not load evaluations")
        return

    evaluations_ref = manifest.get("evaluations", [])
    if not evaluations_ref:
        print("ℹ No evaluations found in this pack.")
        return

    evals_data = None
    if isinstance(evaluations_ref, list) and evaluations_ref:
        first = evaluations_ref[0]
        if isinstance(first, dict) and "$ref" in first:
            evals_data = _load_evaluations(pack_path, first["$ref"])

    if not evals_data or not evals_data.get("evaluations"):
        print("ℹ No evaluation questions available.")
        return

    questions = evals_data["evaluations"]
    correct_count = 0

    print("\n=== Evaluation Quiz ===")
    print(f"Questions: {len(questions)}\n")

    for idx, q in enumerate(questions, 1):
        question_text = q.get("question", f"Question {idx}")
        expected = q.get("expected_answer", "")

        print(f"[{idx}/{len(questions)}] {question_text}")
        user_answer = input("Your answer: ").strip()

        is_correct = _check_answer(user_answer, expected)
        if is_correct:
            correct_count += 1
            print("✓ Correct!\n")
        else:
            print(f"✗ Expected: {expected}\n")

    score = f"{correct_count}/{len(questions)}"
    print(f"Final Score: {score}")
    percent = (correct_count / len(questions)) * 100
    print(f"Percentage: {percent:.0f}%\n")


def _check_answer(user_answer: str, expected: str) -> bool:
    """Check if user answer contains key words from expected answer."""
    if not user_answer or not expected:
        return False

    import string

    def clean_word(w: str) -> str:
        return w.strip(string.punctuation).lower()

    user_words = {clean_word(w) for w in user_answer.split()}
    expected_words = {clean_word(w) for w in expected.split()}
    user_words.discard("")
    expected_words.discard("")

    key_words = [w for w in expected_words if len(w) > 4 and w not in {"package", "okpf", "using"}]
    if not key_words:
        key_words = [w for w in expected_words if len(w) > 3]
    if not key_words:
        key_words = list(expected_words)[:3]

    matched = sum(1 for w in key_words if w in user_words)
    required = max(1, min(3, len(key_words) // 3))

    return matched >= required
